# Generated by Django 5.0.2 on 2024-08-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.DecimalField(decimal_places=0, max_digits=11)),
                ('nome_paciente', models.CharField(help_text='Nome do paciente', max_length=50)),
                ('serviço', models.CharField(choices=[('restauração', 'Restauração'), ('implantes', 'Implantes'), ('limpeza', 'Limpeza'), ('exodontia', 'Exodontia'), ('coroa', 'Coroa'), ('facetas', 'Facetas'), ('lentes de contato', 'Lentes de contato'), ('ortodontia', 'Ortodontia')], max_length=50)),
            ],
        ),
    ]
