# Generated by Django 5.0.2 on 2024-08-08 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_alter_consulta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='sla',
            field=models.CharField(choices=[('oito', '08:00'), ('nove', '09:00'), ('dez', '10:00'), ('onze', '11:00'), ('duas', '14:00'), ('tres', '15:00'), ('quatro', '16:00'), ('cinco', '17:00')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateField(default=datetime.datetime(2024, 8, 8, 19, 6, 0, 569621, tzinfo=datetime.timezone.utc), verbose_name='data'),
        ),
    ]
