# Generated by Django 5.0.2 on 2024-08-08 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_rename_sla_consulta_hora_alter_consulta_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='nome_paciente',
            new_name='nome_do_paciente',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateField(default=datetime.datetime(2024, 8, 8, 19, 8, 59, 469123, tzinfo=datetime.timezone.utc), verbose_name='data'),
        ),
    ]
