# Generated by Django 5.0.2 on 2024-08-08 19:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_rename_nome_paciente_consulta_nome_do_paciente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_dentista', models.CharField(max_length=50)),
                ('CRO', models.DecimalField(decimal_places=0, max_digits=11)),
            ],
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateField(default=datetime.datetime(2024, 8, 8, 19, 18, 17, 89583, tzinfo=datetime.timezone.utc), verbose_name='data'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='dentista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.dentista'),
        ),
    ]
