# Generated by Django 5.0.2 on 2024-08-08 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_dentista_alter_consulta_data_consulta_dentista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateField(default=datetime.datetime(2024, 8, 8, 19, 21, 58, 513471, tzinfo=datetime.timezone.utc), verbose_name='data'),
        ),
    ]
