# Generated by Django 5.0.2 on 2024-08-08 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0013_alter_consulta_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateField(default=datetime.datetime(2024, 8, 8, 19, 48, 13, 676622, tzinfo=datetime.timezone.utc), verbose_name='data'),
        ),
    ]
